var xx;
setTimeout(function () {
    xx = Easy.Grid().SetGridArea('2eb7473bb9614a62a417aa8371faee43')
        .SetUrl('')
        .Limit('20')
        .SearchAble()
        .OrderBy('Type_BaseCode', 1)
        .SetBoolBar('#toolBar')
        .SetExportUrl('https://reports.mberplus.com.au/api/ReportStocks/ExportScreen?CompanyID=190&OrgID=').SetModel({
        "ActionType": {
            "Name": "ActionType",
            "DisplayName": " ",
            "Width": 150,
            "Sortable": false,
            "Searchable": false,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "InventoryCode": {
            "Name": "InventoryCode",
            "DisplayName": "Base_code",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "ProductName": {
            "Name": "ProductName",
            "DisplayName": "Inventory Name",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "Size": {
            "Name": "Size",
            "DisplayName": "Size",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "Variation": {
            "Name": "Variation",
            "DisplayName": "Type",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "Type_BaseCode": {
            "Name": "Type_BaseCode",
            "DisplayName": "Type",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 1,
            "Data": ""
        },
        "ProductStatus": {
            "Name": "ProductStatus",
            "DisplayName": "Status",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "Select",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 0,
            "Data": "<option value='Active'>Active</option><option value='Inactive'>Inactive</option>"
        },
        "WhName": {
            "Name": "WhName",
            "DisplayName": "WH_Name",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "Available": {
            "Name": "Available",
            "DisplayName": "Available",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "Int32",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "SeasonTotal": {
            "Name": "SeasonTotal",
            "DisplayName": "Season Total",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "Int32",
            "DateFormat": null,
            "JsDateFormat": null,
            "ValueDateFormat": null,
            "Hidden": 0,
            "Data": ""
        },
        "ID": {
            "Name": "ID",
            "DisplayName": "ID",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "Int64",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "Type": {
            "Name": "Type",
            "DisplayName": "Type",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "String",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "CompanyID": {
            "Name": "CompanyID",
            "DisplayName": "CompanyID",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "Int32",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "Title": {
            "Name": "Title",
            "DisplayName": "Title",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "Description": {
            "Name": "Description",
            "DisplayName": "Description",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "Status": {
            "Name": "Status",
            "DisplayName": "Status",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "CreateBy": {
            "Name": "CreateBy",
            "DisplayName": "CreateBy",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "CreatebyName": {
            "Name": "CreatebyName",
            "DisplayName": "CreatebyName",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "CreateDate": {
            "Name": "CreateDate",
            "DisplayName": "CreateDate",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "LastUpdateBy": {
            "Name": "LastUpdateBy",
            "DisplayName": "LastUpdateBy",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "LastUpdateByName": {
            "Name": "LastUpdateByName",
            "DisplayName": "LastUpdateByName",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        },
        "LastUpdateDate": {
            "Name": "LastUpdateDate",
            "DisplayName": "LastUpdateDate",
            "Width": 150,
            "Sortable": true,
            "Searchable": true,
            "IsExport": false,
            "DataType": "None",
            "DateFormat": "",
            "JsDateFormat": "",
            "ValueDateFormat": "",
            "Hidden": 1,
            "Data": ""
        }
    }).Show();
}, 500);